# Generated by Django 4.2 on 2023-08-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plan",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Plano",
                "verbose_name_plural": "Planos",
            },
        ),
        migrations.AlterField(
            model_name="plan",
            name="max_adm_account",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Número máximo de adms"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="max_staff_account",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Número máximo de colaboradores"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Nome"),
        ),
    ]
