# Generated by Django 4.2 on 2023-07-28 16:46

import dao.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0001_first_migration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de atualização"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Nome da empresa"),
                ),
                (
                    "cnpj",
                    dao.fields.CnpjField(
                        max_length=14, unique=True, verbose_name="CNPJ"
                    ),
                ),
                (
                    "phone_number",
                    dao.fields.PhoneField(
                        max_length=13, unique=True, verbose_name="Número de telefone"
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="Primeiro nome"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Sobrenome"),
                ),
                (
                    "phone_number",
                    dao.fields.PhoneField(
                        max_length=13, verbose_name="Número de telefone"
                    ),
                ),
                (
                    "is_company_admin",
                    models.BooleanField(
                        default=False, verbose_name="Administrador da empresa?"
                    ),
                ),
                (
                    "is_company_staff",
                    models.BooleanField(
                        default=True, verbose_name="Colaborador da empresa?"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registration.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta",
                "verbose_name_plural": "Contas",
                "ordering": ["-created_at"],
            },
            bases=("authentication.user",),
        ),
    ]
