# Generated by Django 4.2 on 2023-08-05 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0002_alter_plan_options_alter_plan_max_adm_account_and_more"),
        ("registration", "0001_first_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="plan",
            field=models.ForeignKey(
                default=123,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="companies",
                to="subscription.plan",
                verbose_name="Plano",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="account",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="registration.company",
            ),
        ),
    ]
