# Generated by Django 4.2 on 2023-08-05 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0002_company_plan_alter_account_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="registration.company",
            ),
        ),
    ]
