# Generated by Django 4.2 on 2023-08-16 09:10

import dao.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0003_alter_account_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="cpf",
            field=dao.fields.CpfField(
                default=78945612365, max_length=11, unique=True, verbose_name="CPF"
            ),
            preserve_default=False,
        ),
    ]
