# Generated by Django 4.2 on 2023-08-27 10:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("registration", "0004_account_cpf"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de atualização"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nome"),
                ),
                ("definition", models.JSONField(verbose_name="Definição")),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("new_message", "nova mensagem"),
                            ("new_lead", "novo lead"),
                        ],
                        max_length=20,
                        verbose_name="Acionador",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_definitions",
                        to="registration.account",
                        verbose_name="Dono da definição",
                    ),
                ),
            ],
            options={
                "verbose_name": "Definição de Fluxo",
                "verbose_name_plural": "Definições de Fluxo",
                "ordering": ["-created_at"],
            },
        ),
    ]
