# Generated by Django 4.2 on 2023-09-07 22:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0002_alter_lead_owner"),
        ("registration", "0004_account_cpf"),
        ("communication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowElement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de atualização"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("message", "mensagem"),
                            ("answer", "resposta"),
                            ("choice", "opções"),
                            ("delay", "atraso"),
                        ],
                        max_length=20,
                        verbose_name="Nome",
                    ),
                ),
                ("task_started", models.BooleanField(verbose_name="Tarefa inciada?")),
                (
                    "task_finished",
                    models.BooleanField(verbose_name="Tarefa finalizada?"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data do inicio da execução"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data do final da execução"
                    ),
                ),
            ],
            options={
                "verbose_name": "Elemento",
                "verbose_name_plural": "Elementos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageElement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de atualização"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("content", models.TextField()),
                (
                    "flow_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages_element",
                        to="communication.flowelement",
                        verbose_name="Elemento do fluxo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Elemento Mensagem",
                "verbose_name_plural": "Elementos Mensagem",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FlowExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de atualização"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data do inicio da execução"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data do final da execução"
                    ),
                ),
                (
                    "flow_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_executions",
                        to="communication.flowdefinition",
                        verbose_name="Definição do fluxo",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_executions",
                        to="lead.lead",
                        verbose_name="Lead",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_executions",
                        to="registration.account",
                        verbose_name="Dono da definição",
                    ),
                ),
            ],
            options={
                "verbose_name": "Execução de Fluxo",
                "verbose_name_plural": "Execuções de Fluxo",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FlowElementList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de atualização"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "index",
                    models.PositiveIntegerField(default=0, verbose_name="Posição"),
                ),
                (
                    "flow_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_elements_list",
                        to="communication.flowelement",
                        verbose_name="Elemento do fluxo",
                    ),
                ),
                (
                    "flow_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_elements_list",
                        to="communication.flowexecution",
                        verbose_name="Execução do fluxo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lista de Elemento",
                "verbose_name_plural": "Lista de Elementos",
                "ordering": ["-created_at"],
            },
        ),
    ]
