# Generated by Django 4.2 on 2023-09-07 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("communication", "0002_flowelement_messageelement_flowexecution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowelement",
            name="flow_execution",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flow_elements",
                to="communication.flowexecution",
                verbose_name="Execução do fluxo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flowelement",
            name="index",
            field=models.PositiveIntegerField(default=0, verbose_name="Posição"),
        ),
        migrations.AlterField(
            model_name="flowelement",
            name="task_finished",
            field=models.BooleanField(default=False, verbose_name="Tarefa finalizada?"),
        ),
        migrations.AlterField(
            model_name="flowelement",
            name="task_started",
            field=models.BooleanField(default=False, verbose_name="Tarefa inciada?"),
        ),
        migrations.DeleteModel(
            name="FlowElementList",
        ),
    ]
