# Generated by Django 4.2 on 2023-09-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communication", "0003_flowelement_flow_execution_flowelement_index_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowdefinition",
            name="trigger",
            field=models.CharField(
                choices=[("new_message", "NOVA_MENSAGEM"), ("new_lead", "NOVO_LEAD")],
                max_length=20,
                verbose_name="Acionador",
            ),
        ),
        migrations.AlterField(
            model_name="flowelement",
            name="name",
            field=models.CharField(
                choices=[
                    ("message", "MENSAGEM"),
                    ("answer", "RESPOSTA"),
                    ("choice", "ESCOLHA"),
                    ("delay", "ATRASO"),
                ],
                max_length=20,
                verbose_name="Nome",
            ),
        ),
    ]
