# Generated by Django 4.2 on 2023-08-23 23:11

import dao.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("registration", "0004_account_cpf"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de atualização"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="Primeiro nome"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Sobrenome"),
                ),
                (
                    "cpf",
                    dao.fields.CpfField(
                        blank=True, max_length=11, null=True, verbose_name="CPF"
                    ),
                ),
                (
                    "phone_number",
                    dao.fields.PhoneField(
                        max_length=13, unique=True, verbose_name="Número de telefone"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads",
                        to="registration.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads",
                        to="registration.account",
                        verbose_name="Dodo do lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de atualização"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "value",
                    models.CharField(
                        choices=[
                            ("created", "criado"),
                            ("on_touch", "em contato"),
                            ("verified", "verificado"),
                            ("not_verified", "não verificado"),
                        ],
                        default="created",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status",
                        to="lead.lead",
                        verbose_name="Lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status",
                "verbose_name_plural": "Status",
                "ordering": ["-created_at"],
            },
        ),
    ]
